trigger:
  branches:
    include:
      - main   # Runs pipeline when code is pushed to main branch

pool:
  name: SelfHostedAgentToken

stages:
  - stage: Build
    displayName: "Build Zomato App"
    jobs:
      - job: BuildJob
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '18.x'
            displayName: "Use Node.js"

          - script: |
              npm install
              npm run build || echo "No build script found, skipping build"
            displayName: "Install & Build App"

         # - task: PublishBuildArtifacts@1
          #  inputs:
           #   PathtoPublish: '$(System.DefaultWorkingDirectory)'
            #  ArtifactName: 'drop'
             # publishLocation: 'Container'
            #displayName: "Publish Build Artifacts"

  - stage: Deploy
    displayName: "Deploy to Azure WebApp"
    dependsOn: Build
    jobs:
      - deployment: DeployJob
        displayName: "Deploy Application"
        environment: 'dev'
        strategy:
          runOnce:
            deploy:
              steps:
                - task: DownloadBuildArtifacts@0
                  inputs:
                    buildType: 'current'
                    downloadType: 'single'
                    artifactName: 'drop'
                    downloadPath: '$(System.ArtifactsDirectory)'

                - task: AzureWebApp@1
                  inputs:
                    azureSubscription: 'Zomato-ARG'  # replace with your service connection
                    appName: 'Zomato'                   # replace with your App Service name
                    package: '$(System.ArtifactsDirectory)/drop'
