trigger:
  branches:
    include:
      - main   

pool:
  name: SelfHostedAgentToken

stages:
  - stage: Build
    displayName: "Build Zomato App"
    jobs:
      - job: BuildJob
        timeoutInMinutes: 120   
        steps:
          # ✅ Cache node_modules
          - task: Cache@2
            inputs:
              key: 'npm | "$(Agent.OS)" | package-lock.json'
              restoreKeys: |
                npm | "$(Agent.OS)"
              path: $(Pipeline.Workspace)/.npm
            displayName: "Cache npm packages"

          # ✅ Use Node.js (remove this if Node 18 is pre-installed on your self-hosted agent)
          - task: NodeTool@0
            inputs:
              versionSpec: '18.x'
            displayName: "Use Node.js"

          # ✅ Faster install using npm ci
          - script: |
              npm ci --prefer-offline --no-audit
              npm run build || echo "No build script found, skipping build"
            displayName: "Install & Build App"

          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(System.DefaultWorkingDirectory)'
              ArtifactName: 'drop'
              publishLocation: 'Container'
            displayName: "Publish Build Artifacts"

  - stage: Deploy
    displayName: "Deploy to Azure WebApp"
    dependsOn: Build
    jobs:
      - deployment: DeployJob
        displayName: "Deploy Application"
        environment: 'dev'
        timeoutInMinutes: 120   # extend timeout
        strategy:
          runOnce:
            deploy:
              steps:
                - task: DownloadBuildArtifacts@0
                  inputs:
                    buildType: 'current'
                    downloadType: 'single'
                    artifactName: 'drop'
                    downloadPath: '$(System.ArtifactsDirectory)'

                - task: AzureWebApp@1
                  inputs:
                    azureSubscription: 'Zomato-ARG'  # replace with your service connection
                    appName: 'Zomato'                # replace with your App Service name
                    package: '$(System.ArtifactsDirectory)/drop'
